public with sharing class ExpensesConstants {

    // Payment Status Field Values

    public static final String PAYMENT_STATUS_PAID                        = 'Paid';
    public static final String PAYMENT_STATUS_PARTIALLY_PAID    = 'Partially Paid';
    public static final String PAYMENT_STATUS_POSTPONED          = 'Postponed';
    public static final String PAYMENT_STATUS_ON_HOLD               = 'On Hold';
    public static final String PAYMENT_STATUS_CANCELLED           = 'Cancelled';
    public static final String PAYMENT_STATUS_PENDING                = 'Pending';
    public static final String PAYMENT_STATUS_PENDING_SOON    = 'Pending Soon';
    public static final String PAYMENT_STATUS_DUE_TODAY           = 'Due Today';
    public static final String PAYMENT_STATUS_OVERDUE               = 'Overdue';
    public static final String PAYMENT_STATUS_TOTAL_AMOUNT_PAID        = 'Total Amount Paid';
    public static final String PAYMENT_STATUS_MINIMUM_AMOUNT_PAID  = 'Minimum Amount Paid';

}